In [2]:
import numpy as np


In [4]:
oned = np.arange(27)
print(oned)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [19]:
import numpy as np
twod = np.arange(20)

In [20]:
print(twod)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
twod.reshape(3,3,3)

ValueError: cannot reshape array of size 20 into shape (3,3,3)

In [25]:
import cv2


In [26]:
import os
os.listdir()

['smallgray.png', 'numpy.ipynb', '.ipynb_checkpoints']

In [28]:
image=cv2.imread("smallgray.png",0)
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [29]:
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [30]:
image[0:1,2:3]

array([[104]], dtype=uint8)

In [32]:
image.shape

(3, 5)

In [35]:
for i in image.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
